"""
    Space Trader (PalmOS) | RPINerd, 2024

    Game data is stored in this module.
    Each dictionary in this module contains the possible values for a specific game element such
    as government attributes, ship stats, or trade item tech level limits. This was done in an
    effort to declutter the class definition files as much as possible to improve readability.
"""

from .commander import CombatReputation, CriminalRecord
from .constants import Activity, Size, Skills, SocietalPressure, SpecialResource, TechLevel
from .economy import TradeItemId, Ware
from .government import GovernmentId, PoliticalSystem
from .ships import Gadget, GadgetID, SheildID, Shield, Ship, ShipID, Weapon, WeaponID

PLANET_NAMES = {
    0: "Acamar",
    1: "Adahn",
    2: "Aldea",
    3: "Andevian",
    4: "Antedi",
    5: "Balosnee",
    6: "Baratas",
    7: "Bob",
    8: "Brax",
    9: "Bretel",
    10: "Calondia",
    11: "Campor",
    12: "Capelle",
    13: "Carzon",
    14: "Castor",
    15: "Cestus",
    16: "Cheron",
    17: "Courteney",
    18: "Daled",
    19: "Damast",
    20: "Davlos",
    21: "Deneb",
    22: "Deneva",
    23: "Devidia",
    24: "Draylon",
    25: "Drema",
    26: "Endor",
    27: "Esmee",
    28: "Exo",
    29: "Ferris",
    30: "Festen",
    31: "Fourmi",
    32: "Frolix",
    33: "Gemulon",
    34: "Guinifer",
    35: "Hades",
    36: "Hamlet",
    37: "Helena",
    38: "Hulst",
    39: "Iodine",
    40: "Iralius",
    41: "Janus",
    42: "Japori",
    43: "Jarada",
    44: "Jason",
    45: "Kaylon",
    46: "Khefka",
    47: "Kira",
    48: "Klaatu",
    49: "Klaestron",
    50: "Korma",
    51: "Kravat",
    52: "Krios",
    53: "Laertes",
    54: "Largo",
    55: "Lave",
    56: "Ligon",
    57: "Lowry",
    58: "Magrat",
    59: "Malcoria",
    60: "Melina",
    61: "Mentar",
    62: "Merik",
    63: "Mintaka",
    64: "Montor",
    65: "Mordan",
    66: "Myrthe",
    67: "Nelvana",
    68: "Nix",
    69: "Nyle",
    70: "Odet",
    71: "Og",
    72: "Omega",
    73: "Omphalos",
    74: "Orias",
    75: "Othello",
    76: "Parade",
    77: "Penthara",
    78: "Picard",
    79: "Pollux",
    80: "Quator",
    81: "Rakhar",
    82: "Ran",
    83: "Regulas",
    84: "Relva",
    85: "Rhymus",
    86: "Rochani",
    87: "Rubicum",
    88: "Rutia",
    89: "Sarpeidon",
    90: "Sefalla",
    91: "Seltrice",
    92: "Sigma",
    93: "Sol",
    94: "Somari",
    95: "Stakoron",
    96: "Styris",
    97: "Talani",
    98: "Tamus",
    99: "Tantalos",
    100: "Tanuga",
    101: "Tarchannen",
    102: "Terosa",
    103: "Thera",
    104: "Titan",
    105: "Torin",
    106: "Triacus",
    107: "Turkana",
    108: "Tyrus",
    109: "Umberlee",
    110: "Utopia",
    111: "Vadera",
    112: "Vagra",
    113: "Vandor",
    114: "Ventax",
    115: "Xenon",
    116: "Xerxes",
    117: "Yew",
    118: "Yojimbo",
    119: "Zalkon",
    120: "Zuul",
}

GOVERNMENTS = {
    GovernmentId.ANARCHY: PoliticalSystem(
        "Anarchy",
        0,
        Activity.ABSENT,
        Activity.SWARMS,
        Activity.MINIMAL,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.INDUSTRIAL,
        7,
        True,
        True,
        TradeItemId.FOOD,
    ),
    GovernmentId.CAPITALIST: PoliticalSystem(
        "Capitalist",
        2,
        Activity.SOME,
        Activity.FEW,
        Activity.SWARMS,
        TechLevel.EARLY_INDUSTRIAL,
        TechLevel.HI_TECH,
        1,
        True,
        True,
        TradeItemId.ORE,
    ),
    GovernmentId.COMMUNIST: PoliticalSystem(
        "Communist",
        6,
        Activity.ABUNDANT,
        Activity.MODERATE,
        Activity.MODERATE,
        TechLevel.AGRICULTURAL,
        TechLevel.INDUSTRIAL,
        5,
        True,
        True,
        TradeItemId.NONE,
    ),
    GovernmentId.CONFEDERACY: PoliticalSystem(
        "Confederacy",
        5,
        Activity.MODERATE,
        Activity.SOME,
        Activity.MANY,
        TechLevel.AGRICULTURAL,
        TechLevel.POST_INDUSTRIAL,
        3,
        True,
        True,
        TradeItemId.GAMES,
    ),
    GovernmentId.CORPORATE: PoliticalSystem(
        "Corporate",
        2,
        Activity.ABUNDANT,
        Activity.FEW,
        Activity.SWARMS,
        TechLevel.EARLY_INDUSTRIAL,
        TechLevel.HI_TECH,
        2,
        True,
        True,
        TradeItemId.ROBOTS,
    ),
    GovernmentId.CYBERNETIC: PoliticalSystem(
        "Cybernetic",
        0,
        Activity.SWARMS,
        Activity.SWARMS,
        Activity.MANY,
        TechLevel.POST_INDUSTRIAL,
        TechLevel.HI_TECH,
        0,
        False,
        False,
        TradeItemId.ORE,
    ),
    GovernmentId.DEMOCRACY: PoliticalSystem(
        "Democracy",
        4,
        Activity.SOME,
        Activity.FEW,
        Activity.MANY,
        TechLevel.RENAISSANCE,
        TechLevel.HI_TECH,
        2,
        True,
        True,
        TradeItemId.GAMES,
    ),
    GovernmentId.DICTATORSHIP: PoliticalSystem(
        "Dictatorship",
        3,
        Activity.MODERATE,
        Activity.MANY,
        Activity.SOME,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.HI_TECH,
        2,
        True,
        True,
        TradeItemId.NONE,
    ),
    GovernmentId.FASCIST: PoliticalSystem(
        "Fascist",
        7,
        Activity.SWARMS,
        Activity.SWARMS,
        Activity.MINIMAL,
        TechLevel.EARLY_INDUSTRIAL,
        TechLevel.HI_TECH,
        0,
        False,
        True,
        TradeItemId.MACHINERY,
    ),
    GovernmentId.FEUDAL: PoliticalSystem(
        "Feudal",
        1,
        Activity.MINIMAL,
        Activity.ABUNDANT,
        Activity.FEW,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.RENAISSANCE,
        6,
        True,
        True,
        TradeItemId.FIREARMS,
    ),
    GovernmentId.MILITARY: PoliticalSystem(
        "Military",
        7,
        Activity.SWARMS,
        Activity.ABSENT,
        Activity.ABUNDANT,
        TechLevel.MEDIEVAL,
        TechLevel.HI_TECH,
        0,
        False,
        True,
        TradeItemId.ROBOTS,
    ),
    GovernmentId.MONARCHY: PoliticalSystem(
        "Monarchy",
        3,
        Activity.MODERATE,
        Activity.SOME,
        Activity.MODERATE,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.INDUSTRIAL,
        4,
        True,
        True,
        TradeItemId.MEDICINE,
    ),
    GovernmentId.PACIFIST: PoliticalSystem(
        "Pacifist",
        7,
        Activity.FEW,
        Activity.MINIMAL,
        Activity.MANY,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.RENAISSANCE,
        1,
        True,
        False,
        TradeItemId.NONE,
    ),
    GovernmentId.SOCIALIST: PoliticalSystem(
        "Socialist",
        4,
        Activity.FEW,
        Activity.MANY,
        Activity.SOME,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.INDUSTRIAL,
        6,
        True,
        True,
        TradeItemId.NONE,
    ),
    GovernmentId.SATORI: PoliticalSystem(
        "Satori",
        0,
        Activity.MINIMAL,
        Activity.MINIMAL,
        Activity.MINIMAL,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.AGRICULTURAL,
        0,
        False,
        False,
        TradeItemId.NONE,
    ),
    GovernmentId.TECHNOCRACY: PoliticalSystem(
        "Technocracy",
        1,
        Activity.ABUNDANT,
        Activity.SOME,
        Activity.ABUNDANT,
        TechLevel.EARLY_INDUSTRIAL,
        TechLevel.HI_TECH,
        2,
        True,
        True,
        TradeItemId.WATER,
    ),
    GovernmentId.THEOCRACY: PoliticalSystem(
        "Theocracy",
        5,
        Activity.ABUNDANT,
        Activity.MINIMAL,
        Activity.MODERATE,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.EARLY_INDUSTRIAL,
        0,
        True,
        True,
        TradeItemId.NARCOTICS,
    ),
}

GOVT_NAMES = {
    GovernmentId.ANARCHY: "Anarchy",
    GovernmentId.CAPITALIST: "Capitalist",
    GovernmentId.COMMUNIST: "Communist",
    GovernmentId.CONFEDERACY: "Confederacy",
    GovernmentId.CORPORATE: "Corporate",
    GovernmentId.CYBERNETIC: "Cybernetic",
    GovernmentId.DEMOCRACY: "Democracy",
    GovernmentId.DICTATORSHIP: "Dictatorship",
    GovernmentId.FASCIST: "Facist",
    GovernmentId.FEUDAL: "Feudal",
    GovernmentId.MILITARY: "Military",
    GovernmentId.MONARCHY: "Monarchy",
    GovernmentId.PACIFIST: "Pacifist",
    GovernmentId.SOCIALIST: "Socialist",
    GovernmentId.SATORI: "Satori",
    GovernmentId.TECHNOCRACY: "Technocracy",
    GovernmentId.THEOCRACY: "Theocracy",
}

TRADEITEMS = {
    TradeItemId.WATER: Ware(
        "Water",
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.MEDIEVAL,
        30,
        3,
        4,
        SocietalPressure.DROUGHT,
        SpecialResource.SWEETOCEANS,
        SpecialResource.DESERT,
        30,
        50,
        1,
    ),
    TradeItemId.FURS: Ware(
        "Furs",
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.PRE_AGRICULTURAL,
        250,
        10,
        10,
        SocietalPressure.COLD,
        SpecialResource.RICHFAUNA,
        SpecialResource.LIFELESS,
        230,
        280,
        5,
    ),
    TradeItemId.FOOD: Ware(
        "Food",
        TechLevel.AGRICULTURAL,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.AGRICULTURAL,
        100,
        5,
        5,
        SocietalPressure.CROPFAILURE,
        SpecialResource.RICHSOIL,
        SpecialResource.POORSOIL,
        90,
        160,
        5,
    ),
    TradeItemId.ORE: Ware(
        "Ore",
        TechLevel.MEDIEVAL,
        TechLevel.MEDIEVAL,
        TechLevel.RENAISSANCE,
        350,
        20,
        10,
        SocietalPressure.WAR,
        SpecialResource.MINERAL_RICH,
        SpecialResource.MINERAL_POOR,
        350,
        420,
        10,
    ),
    TradeItemId.GAMES: Ware(
        "Games",
        TechLevel.RENAISSANCE,
        TechLevel.AGRICULTURAL,
        TechLevel.POST_INDUSTRIAL,
        250,
        -10,
        5,
        SocietalPressure.BOREDOM,
        SpecialResource.ARTISTIC,
        SpecialResource.NOTHING,
        160,
        270,
        5,
    ),
    TradeItemId.FIREARMS: Ware(
        "Firearms",
        TechLevel.RENAISSANCE,
        TechLevel.AGRICULTURAL,
        TechLevel.INDUSTRIAL,
        1250,
        -75,
        100,
        SocietalPressure.WAR,
        SpecialResource.WARLIKE,
        SpecialResource.NOTHING,
        600,
        1100,
        25,
    ),
    TradeItemId.MEDICINE: Ware(
        "Medicine",
        TechLevel.EARLY_INDUSTRIAL,
        TechLevel.AGRICULTURAL,
        TechLevel.POST_INDUSTRIAL,
        650,
        -20,
        10,
        SocietalPressure.PLAGUE,
        SpecialResource.SPECIALHERBS,
        SpecialResource.NOTHING,
        400,
        700,
        25,
    ),
    TradeItemId.MACHINERY: Ware(
        "Machinery",
        TechLevel.EARLY_INDUSTRIAL,
        TechLevel.RENAISSANCE,
        TechLevel.INDUSTRIAL,
        900,
        -30,
        5,
        SocietalPressure.EMPLOYMENT,
        SpecialResource.NOTHING,
        SpecialResource.NOTHING,
        600,
        800,
        25,
    ),
    TradeItemId.NARCOTICS: Ware(
        "Narrcotics",
        TechLevel.INDUSTRIAL,
        TechLevel.PRE_AGRICULTURAL,
        TechLevel.INDUSTRIAL,
        3500,
        -125,
        150,
        SocietalPressure.BOREDOM,
        SpecialResource.WEIRDMUSHROOMS,
        SpecialResource.NOTHING,
        2000,
        3000,
        50,
    ),
    TradeItemId.ROBOTS: Ware(
        "Robots",
        TechLevel.POST_INDUSTRIAL,
        TechLevel.EARLY_INDUSTRIAL,
        TechLevel.HI_TECH,
        5000,
        -150,
        100,
        SocietalPressure.EMPLOYMENT,
        SpecialResource.NOTHING,
        SpecialResource.NOTHING,
        3500,
        5000,
        100,
    ),
}

SHIPS = {
    ShipID.FLEA: Ship(
        "Flea",
        Size.TINY,
        10,
        0,
        0,
        0,
        1,
        20,
        1,
        25,
        1,
        2000,
        2,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        Activity.ABSENT,
        TechLevel.EARLY_INDUSTRIAL,
    ),
    ShipID.GNAT: Ship(
        "Gnat",
        Size.SMALL,
        15,
        1,
        0,
        1,
        1,
        14,
        1,
        100,
        2,
        10000,
        28,
        Activity.ABSENT,
        Activity.ABSENT,
        Activity.ABSENT,
        TechLevel.INDUSTRIAL,
    ),
    ShipID.FIREFLY: Ship(
        "Firefly",
        Size.SMALL,
        20,
        1,
        1,
        1,
        1,
        17,
        1,
        100,
        3,
        25000,
        20,
        Activity.ABSENT,
        Activity.ABSENT,
        Activity.ABSENT,
        TechLevel.INDUSTRIAL,
    ),
    ShipID.MOSQUITO: Ship(
        "Mosquito",
        Size.SMALL,
        15,
        2,
        1,
        1,
        1,
        13,
        1,
        100,
        5,
        30000,
        20,
        Activity.ABSENT,
        Activity.MINIMAL,
        Activity.ABSENT,
        TechLevel.INDUSTRIAL,
    ),
    ShipID.BUMBLEBEE: Ship(
        "Bumblebee",
        Size.MEDIUM,
        25,
        1,
        2,
        2,
        2,
        15,
        1,
        100,
        7,
        60000,
        15,
        Activity.MINIMAL,
        Activity.MINIMAL,
        Activity.ABSENT,
        TechLevel.INDUSTRIAL,
    ),
    ShipID.BEETLE: Ship(
        "Beetle",
        Size.MEDIUM,
        50,
        0,
        1,
        1,
        3,
        14,
        1,
        50,
        10,
        80000,
        3,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        Activity.ABSENT,
        TechLevel.INDUSTRIAL,
    ),
    ShipID.HORNET: Ship(
        "Hornet",
        Size.LARGE,
        20,
        3,
        2,
        1,
        2,
        16,
        2,
        150,
        15,
        100000,
        6,
        Activity.FEW,
        Activity.SOME,
        Activity.MINIMAL,
        TechLevel.POST_INDUSTRIAL,
    ),
    ShipID.GRASSHOPPER: Ship(
        "Grasshopper",
        Size.LARGE,
        30,
        2,
        2,
        3,
        3,
        15,
        3,
        150,
        15,
        150000,
        2,
        Activity.SOME,
        Activity.MODERATE,
        Activity.FEW,
        TechLevel.POST_INDUSTRIAL,
    ),
    ShipID.TERMITE: Ship(
        "Termite",
        Size.HUGE,
        60,
        1,
        3,
        2,
        3,
        13,
        4,
        200,
        20,
        225000,
        2,
        Activity.MODERATE,
        Activity.MANY,
        Activity.SOME,
        TechLevel.HI_TECH,
    ),
    ShipID.WASP: Ship(
        "Wasp",
        Size.HUGE,
        35,
        3,
        2,
        2,
        3,
        14,
        5,
        200,
        20,
        300000,
        2,
        Activity.MANY,
        Activity.ABUNDANT,
        Activity.MODERATE,
        TechLevel.HI_TECH,
    ),
    # The ships below can't be bought (mostly)
    ShipID.SPACEMONSTER: Ship(
        "Space Monster",
        Size.HUGE,
        0,
        3,
        0,
        0,
        1,
        1,
        1,
        500,
        1,
        500000,
        0,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        TechLevel.UNAVAILABLE,
    ),
    ShipID.DRAGONFLY: Ship(
        "Dragonfly",
        Size.SMALL,
        0,
        2,
        3,
        2,
        1,
        1,
        1,
        10,
        1,
        500000,
        0,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        TechLevel.UNAVAILABLE,
    ),
    ShipID.MANTIS: Ship(
        "Mantis",
        Size.MEDIUM,
        0,
        3,
        1,
        3,
        3,
        1,
        1,
        300,
        1,
        500000,
        0,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        TechLevel.UNAVAILABLE,
    ),
    ShipID.SCARAB: Ship(
        "Scarab",
        Size.LARGE,
        20,
        2,
        0,
        0,
        2,
        1,
        1,
        400,
        1,
        500000,
        0,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        TechLevel.UNAVAILABLE,
    ),
    ShipID.SCORPION: Ship(
        "Scorpion",
        Size.HUGE,
        30,
        2,
        2,
        2,
        2,
        1,
        1,
        300,
        1,
        500000,
        0,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        Activity.UNAVAILABLE,
        TechLevel.UNAVAILABLE,
    ),
}

WEAPONS = {
    WeaponID.PULSELASER: Weapon(WeaponID.PULSELASER, 15, False, 2000, TechLevel.INDUSTRIAL, 50),
    WeaponID.BEAMLASER: Weapon(WeaponID.BEAMLASER, 25, False, 12500, TechLevel.POST_INDUSTRIAL, 35),
    WeaponID.MILITARYLASER: Weapon(WeaponID.MILITARYLASER, 35, False, 35000, TechLevel.HI_TECH, 15),
    WeaponID.MORGANSLASER: Weapon(WeaponID.MORGANSLASER, 85, False, 50000, TechLevel.UNAVAILABLE, 0),
    WeaponID.PHOTONDISRUPTOR: Weapon(WeaponID.PHOTONDISRUPTOR, 20, True, 15000, TechLevel.UNAVAILABLE, 0),
    WeaponID.QUANTUMDISRUPTOR: Weapon(WeaponID.QUANTUMDISRUPTOR, 60, True, 50000, TechLevel.UNAVAILABLE, 0),
}

SHIELDS = {
    SheildID.ENERGY: Shield(SheildID.ENERGY, 100, 5000, TechLevel.INDUSTRIAL, 70),
    SheildID.REFLECTIVE: Shield(SheildID.REFLECTIVE, 200, 20000, TechLevel.POST_INDUSTRIAL, 30),
    SheildID.LIGHTNING: Shield(SheildID.LIGHTNING, 350, 45000, TechLevel.UNAVAILABLE, 0),
}

GADGETS = {
    GadgetID.CARGOBAYS: Gadget(GadgetID.CARGOBAYS, Skills.NONE, 2500, TechLevel.EARLY_INDUSTRIAL, 35),
    GadgetID.AUTOREPAIR: Gadget(GadgetID.AUTOREPAIR, Skills.ENGINEER, 7500, TechLevel.INDUSTRIAL, 20),
    GadgetID.NAVIGATION: Gadget(GadgetID.NAVIGATION, Skills.PILOT, 15000, TechLevel.POST_INDUSTRIAL, 20),
    GadgetID.TARGETING: Gadget(GadgetID.TARGETING, Skills.FIGHTER, 2500, TechLevel.POST_INDUSTRIAL, 20),
    GadgetID.CLOAKING: Gadget(GadgetID.CLOAKING, Skills.PILOT, 100000, TechLevel.HI_TECH, 5),
    # Gadgets below can't be bought
    GadgetID.FUELCOMPACTOR: Gadget(GadgetID.FUELCOMPACTOR, Skills.NONE, 30000, TechLevel.UNAVAILABLE, 0),
    GadgetID.SMUGGLERHOLD: Gadget(GadgetID.SMUGGLERHOLD, Skills.NONE, 60000, TechLevel.UNAVAILABLE, 0),
}

POLICE_RECORDS = {
    CriminalRecord.PSYCHOPATH: -100,
    CriminalRecord.VILLAIN: -70,
    CriminalRecord.CRIMINAL: -30,
    CriminalRecord.CROOK: -10,
    CriminalRecord.DUBIOUS: -5,
    CriminalRecord.CLEAN: 0,
    CriminalRecord.LAWFUL: 5,
    CriminalRecord.TRUSTED: 10,
    CriminalRecord.LIKED: 25,
    CriminalRecord.HERO: 75,
    CriminalRecord.ERRNO: 100,
}

REPUTATION = {
    CombatReputation.HARMLESS: 0,
    CombatReputation.MOSTLY_HARMLESS: 10,
    CombatReputation.POOR: 20,
    CombatReputation.AVERAGE: 40,
    CombatReputation.ABOVE_AVERAGE: 80,
    CombatReputation.COMPETENT: 150,
    CombatReputation.DANGEROUS: 300,
    CombatReputation.DEADLY: 600,
    CombatReputation.ELITE: 1500,
    CombatReputation.BORG: 3000,
}
